name: Deploy Dev
on:
  push:
    branches:
      - feature/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Setup:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'

      - name: Check NPM Version
        run: npm -v

      - name: Check Node Version
        run: node -v

      - name: Install Dependencies
        run: npm install

      - name: Security Audit
        continue-on-error: true
        run: npm audit

  Lint:
    needs: Setup
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'
      - run: npm run lint

  UnitTest:
    needs: Setup
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'
      - run: npm run test:unit

  Build:
    needs: [Lint, UnitTest]
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'
      - run: npm run build-dev
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  DeployDevelop:
    needs: Build
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-northeast-1"
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Deploy to S3
        run: aws s3 cp --recursive dist s3://${{ secrets.S3_DEV_BUCKET_NAME }}
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DEV_DISTRIBUTION_ID }} --paths "/*"

  DeployCloudFormation:
    needs: DeployDevelop
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_GLOBAL_CERTIFICATE_ARN: ${{ secrets.AWS_GLOBAL_CERTIFICATE_ARN }}
      AWS_DEFAULT_REGION: "ap-northeast-1"
    steps:
      - uses: actions/checkout@v4
      - name: Deploy CloudFormation APIGW Template
        run: |
          aws cloudformation deploy \
            --template-file ./aws/templates/api-gateway.yml \
            --stack-name uji52com-dev-apigw \
            --parameter-overrides EmailSNSTopicArn=${{ secrets.EMAIL_SNS_TOPIC_ARN }} Environment=dev \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy CloudFormation Cognito Template
        run: |
          aws cloudformation deploy \
            --template-file ./aws/templates/cognito.yml \
            --stack-name uji52com-dev-cognito \
            --parameter-overrides \
              GoogleClientId=${{ secrets.OIDC_GOOGLE_CLIENT_ID }} \
              GoogleClientSecret=${{ secrets.OIDC_GOOGLE_CLIENT_SECRET }} \
              FromMailAddress=${{ secrets.FROM_EMAIL_ADDRESS }} \
              Environment=dev \
            --capabilities CAPABILITY_NAMED_IAM
