name: Deploy Prd
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  Deploy:
    runs-on: ubuntu-24.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-northeast-1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: aws s3 cp --recursive --region ${{ env.AWS_DEFAULT_REGION }} dist s3://${{ secrets.S3_PRD_BUCKET_NAME }}

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_PRD_DISTRIBUTION_ID }} --paths "/*"
