name: Deploy Dev (calls reusable CI)

on:
  push:
    branches:
      - feature/*
      - feature/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-ci:
    uses: ./.github/workflows/ci-deploy-reusable.yml
    with:
      ref: ${{ github.sha }}
      run_build: true
      run_deploy: true
    secrets: inherit
