name: PR Checks (calls reusable CI)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call-ci:
    uses: ./.github/workflows/ci-deploy-reusable.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      run_build: false
      run_deploy: false
